# You have to setup the environment variables in `/source/.env` before running compose up
version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456 
      POSTGRES_DB: postgres
    volumes:
      - hnp-memories-postgres:/var/lib/postgresql/data
      - ./docker/db-init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    expose:
      - 5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://memories:123456@postgres/memories_hnp
    entrypoint: ["/bin/sh", "/root/app/start-server.sh"]
    

volumes:
  # Create this volume by yourself!!!
  # This prevents the database from being overriden when compose down & up
  hnp-memories-postgres:
    external: true