# You have to setup the environment variables in `/docker/django/.env` before running compose up
# This file mainly serves my need to run PostgreSQL in Docker (to avoid filling my laptop with garbage files)
# I don't really intend to dockerize Django as well (running it in my local environment is good enough for development)

version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456 
      POSTGRES_DB: postgres
    volumes:
      - hnp-memories-postgres:/var/lib/postgresql/data
      - ./docker/postgres/db-init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  web:
    build:
      context: .
      dockerfile: ./docker/django/django.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./docker/django/.django.env
    entrypoint: ["/bin/sh", "/root/app/start-server.sh"]
    

volumes:
  # Create this volume by yourself!!!
  # This prevents the database from being overriden when compose down & up
  hnp-memories-postgres:
    external: true