# Generated by Django 4.0.5 on 2022-06-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_profile_avatar_link_profile_avatar_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date created"),
        ),
    ]
